export default {
  SET_ERROR: 'SET_ERROR',
  SET_VERSION: 'SET_VERSION',
  SET_LOADING: 'SET_LOADING',
  SET_FETCHING_MODELS: 'SET_FETCHING_MODELS',
  SET_INITIALIZED: 'SET_INITIALIZED',
  SET_MODEL: 'SET_MODEL',
  SET_PAGE: 'SET_PAGE',
  SET_MODEL_TYPE: 'SET_MODEL_TYPE',
  SET_COLLECTION_SIZE: 'SET_COLLECTION_SIZE',
  SET_MAPMARKERS: 'SET_MAPMARKERS',
  INITIALIZE: 'INITIALIZE',
};
