export default {
  SET_ERROR: 'SET_ERROR',
  SET_LOADING: 'SET_LOADING',
  SET_INITIALIZED: 'SET_INITIALIZED',
  SET_HAS_PASSED_AGE_GATE: 'SET_HAS_PASSED_AGE_GATE',
  SET_MY_ACCOUNT: 'SET_MY_ACCOUNT',
  SET_AUTHORIZED: 'SET_AUTHORIZED',
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_SIDEBAR_VISIBLE: 'SET_SIDEBAR_VISIBLE',

  /*
    S i g n
      U p
  */
  SET_SIGN_UP_FORM_EMAIL: 'SET_SIGN_UP_FORM_EMAIL',
  SET_SIGN_UP_FORM_EMAIL_AGAIN: 'SET_SIGN_UP_FORM_EMAIL_AGAIN',
  SET_SIGN_UP_FORM_PASSWORD: 'SET_SIGN_UP_FORM_PASSWORD',
  SET_SIGN_UP_FORM_PASSWORD_AGAIN: 'SET_SIGN_UP_FORM_PASSWORD_AGAIN',
  
  /*
    S i g n
      I n
  */
  SET_SIGN_IN_FORM_EMAIL: 'SET_SIGN_IN_FORM_EMAIL',
  SET_SIGN_IN_FORM_PASSWORD: 'SET_SIGN_IN_FORM_PASSWORD',
  
  /*
    C h a n g e
      P a s s w o r d
  */
  SET_CHANGE_PASSWORD_FORM_PASSWORD: 'SET_CHANGE_PASSWORD_FORM_PASSWORD',
  SET_CHANGE_PASSWORD_FORM_PASSWORD_AGAIN: 'SET_CHANGE_PASSWORD_FORM_PASSWORD_AGAIN',
  
  /*
    U p l o a d
      P i e c e
  */
  SET_UPLOAD_PIECE_FORM_IMAGE: 'SET_UPLOAD_PIECE_FORM_IMAGE',
  SET_UPLOAD_PIECE_FORM_TITLE: 'SET_UPLOAD_PIECE_FORM_TITLE',
  SET_UPLOAD_PIECE_FORM_PRICE: 'SET_UPLOAD_PIECE_FORM_PRICE',
  SET_UPLOAD_PIECE_FORM_DESCRIPTION: 'SET_UPLOAD_PIECE_FORM_DESCRIPTION',

  /*
    E d i t
      P i e c e

  */
  SET_EDIT_PIECE_FORM_TITLE: 'SET_EDIT_PIECE_FORM_TITLE',
  SET_EDIT_PIECE_FORM_PRICE: 'SET_EDIT_PIECE_FORM_PRICE',
  SET_EDIT_PIECE_FORM_DESCRIPTION: 'SET_EDIT_PIECE_FORM_DESCRIPTION',

  /*
    E x p l o r e
      S h o p s
  */
  SET_LOCAL_SHOPS: 'SET_LOCAL_SHOPS',
  SET_LOCAL_SHOPS_PAGE: 'SET_LOCAL_SHOPS_PAGE',

  /*
    E x p l o r e
      P i e c e s
  */
  SET_LOCAL_PIECES: 'SET_LOCAL_PIECES',
  SET_LOCAL_PIECES_PAGE: 'SET_LOCAL_PIECES_PAGE',

  /*
    A r t i s t s
  */
  SET_ARTIST: 'SET_ARTIST',
  SET_ACTIVE_ARTIST: 'SET_ACTIVE_ARTIST',

  /*
    S h o p s
  */
  SET_SHOP: 'SET_SHOP',
  SET_ACTIVE_SHOP: 'SET_ACTIVE_SHOP',
  SET_FETCHING_SHOPS: 'SET_FETCHING_SHOPS',

  /*
    P i e c e s
  */
  SET_PIECE: 'SET_PIECE',
  SET_ACTIVE_PIECE: 'SET_ACTIVE_PIECE',
  SET_FETCHING_PIECES: 'SET_FETCHING_PIECES',
  DELETE_PIECE: 'DELETE_PIECE',
};
