export default {
  SET_ERROR: 'SET_ERROR',
  SET_LOADING: 'SET_LOADING',
  SET_INITIALIZED: 'SET_INITIALIZED',

  SET_HAS_PASSED_AGE_GATE: 'SET_HAS_PASSED_AGE_GATE',

  SET_MY_ACCOUNT: 'SET_MY_ACCOUNT',

  SET_AUTHORIZED: 'SET_AUTHORIZED',
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',

  SET_SIGN_UP_FORM_EMAIL: 'SET_SIGN_UP_FORM_EMAIL',
  SET_SIGN_UP_FORM_EMAIL_AGAIN: 'SET_SIGN_UP_FORM_EMAIL_AGAIN',
  SET_SIGN_UP_FORM_PASSWORD: 'SET_SIGN_UP_FORM_PASSWORD',
  SET_SIGN_UP_FORM_PASSWORD_AGAIN: 'SET_SIGN_UP_FORM_PASSWORD_AGAIN',

  SET_SIGN_IN_FORM_EMAIL: 'SET_SIGN_IN_FORM_EMAIL',
  SET_SIGN_IN_FORM_PASSWORD: 'SET_SIGN_IN_FORM_PASSWORD',

  SET_CHANGE_PASSWORD_FORM_PASSWORD: 'SET_CHANGE_PASSWORD_FORM_PASSWORD',
  SET_CHANGE_PASSWORD_FORM_PASSWORD_AGAIN: 'SET_CHANGE_PASSWORD_FORM_PASSWORD_AGAIN',
};
